apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-app-deployment
  namespace: bandera-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-app
  template:
    metadata:
      labels:
        app: java-app
    spec:
      serviceAccountName: default
      containers:
        - name: java-app
          image: openjdk:17-slim
          ports:
            - containerPort: 8080
          env:
            - name: MONGO_URI
              value: "mongodb://mongo-service:27017"   
          volumeMounts:
            - name: java-app-volume
              mountPath: /app  # 
      volumes:
        - name: java-app-volume
          emptyDir: {}   

---
apiVersion: v1
kind: Service
metadata:
  name: java-app-service
spec:
  selector:
    app: java-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
